micronaut:
  application:
    name: keymangergrpc

#datasources:
#  default:
#    url: jdbc:mysql://localhost:3306/pix_keymanager_grpc?createDatabaseIfNotExist=true&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: '123456'
#jpa.default.properties.hibernate.hbm2ddl.auto: update

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/pix_keymanager_grpc`}
    driverClassName: ${DRIVER:org.postgresql.Driver}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    schema-generate: CREATE_DROP
    dialect: ${DIALECT:POSTGRES}
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: ${ITAU_URL:`http://localhost:9091`}